
import { VerticalBox , ScrollView} from "std-widgets.slint";
@rust-attr(derive(serde::Serialize, serde::Deserialize))
export enum DynType {
    Empty,
    Text,
    Component
}

@rust-attr(derive(serde::Serialize, serde::Deserialize))
export struct DynItem {
    dtype: DynType,
    value-text: string
}

component DCTextLine inherits TextInput {
    horizontal-alignment: left;
    vertical-alignment: top;
    min-height: 18px;
    vertical-stretch: 0;
    padding: 0;
    width: 100%;
    wrap: word-wrap;
    read-only: true;
    single-line: false;
    x: 0;
}

export component DynamicContent inherits Rectangle {
    in property<string> name;
    in property<[DynItem]> content;
    padding: 0;
    vertical-stretch: 1;
    horizontal-stretch: 1;
    clip: false;
    ScrollView {
        width: root.width;
        viewport-width: root.width;
        height: root.height;
        viewport-height: root.height * 2;
        x: 0;
        viewport-x: 0;
        y: 0;
        viewport-y: 0;
        VerticalLayout {
            x: 0;
            y: 0;
            padding: 0;
            spacing: 0;
            width: root.width;
            min-height: root.height;
            vertical-stretch: 0;
            for item in content : DCTextLine {
                text: item.value-text;
            }
            Rectangle { vertical-stretch: 1; }
        }
    }
}